// <auto-generated>Ported from the monolith by port-monolith-dotnet — a verbatim relocation.
// Only the // CW-SEAM[...] markers below need an LLM edit; everything else is carried as-is.</auto-generated>
#nullable enable
using Microsoft.EntityFrameworkCore;
using Inventory.Domain;
using Inventory.Infrastructure;

namespace Inventory;

public class InventoryService(InventoryDbContext db)
{
    public async Task<bool> Reserve(int productId, int qty)
    {
        var item = await db.StockItems.FirstOrDefaultAsync(s => s.ProductId == productId);
        if (item is null || item.Quantity < qty) return false;
        item.Quantity -= qty;               // NOTE: read-check-then-write — the oversell seam
        return true;
    }
}
