// <auto-generated>Ported from the monolith by port-monolith-dotnet — a verbatim relocation.
// Only the // CW-SEAM[...] markers below need an LLM edit; everything else is carried as-is.</auto-generated>
#nullable enable
using Microsoft.AspNetCore.Mvc;
using Orders.Domain;

namespace Orders.Controllers;

[ApiController]
[Route("orders")]
public class OrdersController(OrderService orders) : ControllerBase
{
    public record PlaceOrderRequest(int CustomerId, List<LineDto> Lines);
    public record LineDto(int ProductId, int Quantity);

    [HttpPost]
    public async Task<IActionResult> Place([FromBody] PlaceOrderRequest req)
    {
        var order = await orders.PlaceOrder(req.CustomerId, req.Lines.Select(l => (l.ProductId, l.Quantity)));
        return Ok(order);
    }
}
