apiVersion: v1
kind: Secret
metadata:
  name: catalog-secrets
  namespace: acmeplatform
type: Opaque
stringData:
  ConnectionStrings__catalogdb: "Host=catalog-db;Port=5432;Database=catalogdb;Username=postgres;Password=postgres"
  ConnectionStrings__rabbitmq: "amqp://guest:guest@rabbitmq:5672"
