// <auto-generated>Ported from the monolith by port-monolith-dotnet — a verbatim relocation.
// Only the // CW-SEAM[...] markers below need an LLM edit; everything else is carried as-is.</auto-generated>
#nullable enable
using Microsoft.AspNetCore.Mvc;
using Customers.Domain;

namespace Customers.Controllers;

[ApiController]
[Route("customers")]
public class CustomersController(CustomerService customers) : ControllerBase
{
    [HttpGet("{id:int}")]
    public async Task<IActionResult> Get(int id)
    {
        var c = await customers.Get(id);
        return c is null ? NotFound() : Ok(c);
    }
}
