// <auto-generated>Ported from the monolith by port-monolith-dotnet — a verbatim relocation.
// Only the // CW-SEAM[...] markers below need an LLM edit; everything else is carried as-is.</auto-generated>
#nullable enable
using Orders.Domain;
using Orders.Infrastructure;
using Orders.Clients;
using Orders.Features.CreateOrder;
using Wolverine.EntityFrameworkCore;

namespace Orders;

/// Raised when a remote participant refuses the order for a business reason
/// (inactive customer, no stock). Distinct from a transport fault, which retries.
public sealed class OrderRejectedException(string reason) : Exception(reason);

public class OrderService(
    OrdersDbContext db,
    ICatalogClient catalog,
    ICustomersClient customers,
    IInventoryClient inventory,
    IDbContextOutbox outbox)
{
    public async Task<Order> PlaceOrder(int customerId, IEnumerable<(int productId, int qty)> items)
    {
        if (!await customers.IsActiveAsync(customerId))
            throw new OrderRejectedException("customer inactive");

        var order = new Order { CustomerId = customerId, Status = OrderStatuses.Pending };
        var reserved = new List<ReservedLine>();
        decimal total = 0;

        try
        {
            foreach (var (productId, qty) in items)
            {
                // Reserving before pricing keeps the pivot (the charge) last: a
                // reservation is cheap to release, a charge is not.
                if (!await inventory.ReserveAsync(productId, qty))
                    throw new OrderRejectedException("out of stock");

                var price = await catalog.PriceOfAsync(productId);
                reserved.Add(new ReservedLine(productId, qty, price));
                order.Lines.Add(new OrderLine { ProductId = productId, Quantity = qty, UnitPrice = price });
                total += price * qty;
            }
        }
        catch
        {
            // Nothing is persisted yet and no money has moved, so the only
            // compensation owed is releasing the reservations already taken.
            await ReleaseAsync(reserved);
            throw;
        }

        order.Total = total;
        db.Orders.Add(order);

        // The cross-context writes are remote now, so one DbContext transaction can
        // no longer span them. This commits only THIS service's rows plus the saga
        // start message, atomically, through the Wolverine EF outbox; the saga then
        // drives the charge (the pivot) and compensates in reverse if it fails.
        outbox.Enroll(db);
        await outbox.PublishAsync(new CreateOrderStarted(
            CorrelationId: Guid.NewGuid(),
            OrderId: order.Id,
            CustomerId: customerId,
            Lines: reserved,
            Total: total));
        await outbox.SaveChangesAndFlushMessagesAsync();

        return order;
    }

    private async Task ReleaseAsync(IEnumerable<ReservedLine> lines)
    {
        foreach (var line in lines)
        {
            // A failed release must not mask the original failure; the saga's
            // ReleaseStock compensation retries durably.
            try { await inventory.ReleaseAsync(line.ProductId, line.Quantity); }
            catch (HttpRequestException) { }
        }
    }
}
