using Microsoft.AspNetCore.Authentication.JwtBearer;
using Wolverine;   // UseWolverine + policies
using Wolverine.Postgresql;   // PersistMessagesWith* durable store extension
using Orders.Features.Order;  // MapOrderEndpoints

var builder = WebApplication.CreateBuilder(args);

builder.AddServiceDefaults();          // discovery + OpenTelemetry + resilience + health
builder.Services.AddProblemDetails();  // RFC 9457 error shape
builder.Host.UseWolverine(opts =>
{
// Transactional outbox (no dual-write) + durable inbox (idempotent, at-least-once).
if (builder.Configuration.GetValue("Messaging:Durable", true))
{
opts.PersistMessagesWithPostgresql(builder.Configuration.GetConnectionString("ordersdb")!);
opts.UseEntityFrameworkCoreTransactions();             // SaveChanges + outgoing flush atomic
opts.Policies.AutoApplyTransactions();                 // wrap each handler in a transaction
opts.Policies.UseDurableInboxOnAllListeners();          // idempotent consumer (dedup)
opts.Policies.UseDurableOutboxOnAllSendingEndpoints();  // transactional outbox on every publisher
}
// The CreateOrder saga + its step/compensation handlers live in Features/CreateOrder.
opts.Discovery.IncludeAssembly(typeof(Orders.Features.CreateOrder.CreateOrderSaga).Assembly);
});

// Authentication — the token is re-validated inside the service (defence in
// depth: the gateway authenticates at the edge, each service authorizes).
var authEnabled = !string.IsNullOrWhiteSpace(builder.Configuration["Auth:Authority"]);
if (authEnabled)
{
    builder.Services.AddAuthentication(JwtBearerDefaults.AuthenticationScheme)
        .AddJwtBearer(options =>
        {
            options.Authority = builder.Configuration["Auth:Authority"];
            options.Audience = builder.Configuration["Auth:Audience"];
            options.RequireHttpsMetadata = builder.Environment.IsProduction();
        });
    builder.Services.AddAuthorization();
}

// This service's own schema (database-per-service) plus the Wolverine EF outbox
// integration, so the saga's SaveChanges and its outgoing messages commit together.
builder.Services.AddDbContextWithWolverineIntegration<Orders.Infrastructure.OrdersDbContext>(o =>
    o.UseNpgsql(builder.Configuration.GetConnectionString("ordersdb")));

// The extracted business rule and its slice handler.
builder.Services.AddScoped<Orders.OrderService>();
builder.Services.AddScoped<Orders.Features.Order.OrderHandler>();

// Request validation — registered per type (the assembly-scanning extensions live
// in a package this service does not reference).
builder.Services.AddScoped<IValidator<Orders.Features.Order.PlaceOrderRequest>,
    Orders.Features.Order.PlaceOrderRequestValidator>();
builder.Services.AddScoped<IValidator<Orders.Features.Order.OrderLineRequest>,
    Orders.Features.Order.OrderLineRequestValidator>();

// <auto-generated> CW-PORT: register the ported typed clients + gRPC for DI
builder.Services.AddHttpClient<Orders.Clients.ICatalogClient, Orders.Clients.CatalogClient>(c => c.BaseAddress = new("https+http://catalog"));
builder.Services.AddHttpClient<Orders.Clients.ICustomersClient, Orders.Clients.CustomersClient>(c => c.BaseAddress = new("https+http://customers"));
builder.Services.AddHttpClient<Orders.Clients.IInventoryClient, Orders.Clients.InventoryClient>(c => c.BaseAddress = new("https+http://inventory"));
builder.Services.AddHttpClient<Orders.Clients.IPaymentsClient, Orders.Clients.PaymentsClient>(c => c.BaseAddress = new("https+http://payments"));

var app = builder.Build();

app.UseExceptionHandler();
if (authEnabled)
{
    app.UseAuthentication();
    app.UseAuthorization();
}
app.MapDefaultEndpoints();              // /health + /alive

app.MapOrderEndpoints(authEnabled);

app.Run();

// Exposed so the integration test project can host the app via WebApplicationFactory<Program>.
public partial class Program { }
