// <auto-generated>Ported from the monolith by port-monolith-dotnet — a verbatim relocation.
// Only the // CW-SEAM[...] markers below need an LLM edit; everything else is carried as-is.</auto-generated>
#nullable enable
using Microsoft.EntityFrameworkCore;
using Customers.Domain;
using Customers.Infrastructure;

namespace Customers;

public class CustomerService(CustomersDbContext db)
{
    public async Task<Customer?> Get(int id) =>
        await db.Customers.FirstOrDefaultAsync(c => c.Id == id);

    public async Task<bool> IsActive(int id) => (await Get(id))?.Active ?? false;
}
