apiVersion: v1
kind: Secret
metadata:
  name: customers-secrets
  namespace: acmeplatform
type: Opaque
stringData:
  ConnectionStrings__customersdb: "Host=customers-db;Port=5432;Database=customersdb;Username=postgres;Password=postgres"
  ConnectionStrings__rabbitmq: "amqp://guest:guest@rabbitmq:5672"
