// <auto-generated>Ported from the monolith by port-monolith-dotnet — a verbatim relocation.
// Only the // CW-SEAM[...] markers below need an LLM edit; everything else is carried as-is.</auto-generated>
#nullable enable
namespace Customers.Domain;

public class Customer
{
    public int Id { get; set; }
    public string Email { get; set; } = "";
    public bool Active { get; set; } = true;
}
