// <auto-generated>Ported from the monolith by port-monolith-dotnet — a verbatim relocation.
// Only the // CW-SEAM[...] markers below need an LLM edit; everything else is carried as-is.</auto-generated>
#nullable enable
using Microsoft.EntityFrameworkCore;
using Catalog.Domain;
using Catalog.Infrastructure;

namespace Catalog;

public class CatalogService(CatalogDbContext db)
{
    public async Task<Product?> GetProduct(int id) =>
        await db.Products.FirstOrDefaultAsync(p => p.Id == id);

    public async Task<decimal> PriceOf(int productId) =>
        (await GetProduct(productId))?.Price ?? 0m;
}
