apiVersion: v1
kind: ConfigMap
metadata:
  name: orders-config
  namespace: acmeplatform
data:
  ASPNETCORE_ENVIRONMENT: "Production"
  ASPNETCORE_HTTP_PORTS: "8080"
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector:4317"
  OTEL_SERVICE_NAME: "orders"
  Auth__Authority: ""        # e.g. https://keycloak.example.com/realms/acme
  Auth__Audience: "account"
