apiVersion: v1
kind: Secret
metadata:
  name: orders-secrets
  namespace: acmeplatform
type: Opaque
stringData:
  ConnectionStrings__ordersdb: "Host=orders-db;Port=5432;Database=ordersdb;Username=postgres;Password=postgres"
  ConnectionStrings__rabbitmq: "amqp://guest:guest@rabbitmq:5672"
