apiVersion: v1
kind: Service
metadata:
  name: orders
  namespace: acmeplatform
  labels:
    app: orders
spec:
  selector:
    app: orders
  ports:
    - name: http
      port: 80
      targetPort: http
