apiVersion: v1
kind: Secret
metadata:
  name: payments-secrets
  namespace: acmeplatform
type: Opaque
stringData:
  ConnectionStrings__paymentsdb: "Host=payments-db;Port=5432;Database=paymentsdb;Username=postgres;Password=postgres"
  ConnectionStrings__rabbitmq: "amqp://guest:guest@rabbitmq:5672"
