// <auto-generated>Ported from the monolith by port-monolith-dotnet — a verbatim relocation.
// Only the // CW-SEAM[...] markers below need an LLM edit; everything else is carried as-is.</auto-generated>
#nullable enable
using Microsoft.AspNetCore.Mvc;
using Catalog.Domain;

namespace Catalog.Controllers;

[ApiController]
[Route("catalog")]
public class CatalogController(CatalogService catalog) : ControllerBase
{
    [HttpGet("products/{id:int}")]
    public async Task<IActionResult> Get(int id)
    {
        var p = await catalog.GetProduct(id);
        return p is null ? NotFound() : Ok(p);
    }
}
