// <auto-generated>Ported from the monolith by port-monolith-dotnet — a verbatim relocation.
// Only the // CW-SEAM[...] markers below need an LLM edit; everything else is carried as-is.</auto-generated>
#nullable enable
using Microsoft.EntityFrameworkCore;
using Orders.Domain;

namespace Orders.Infrastructure;

/// Per-service context (database-per-service): only orders's own tables.
public class OrdersDbContext(DbContextOptions<OrdersDbContext> options) : DbContext(options)
{
    public DbSet<Order> Orders => Set<Order>();
    public DbSet<OrderLine> OrderLines => Set<OrderLine>();
}
