// <auto-generated>Ported from the monolith by port-monolith-dotnet — a verbatim relocation.
// Only the // CW-SEAM[...] markers below need an LLM edit; everything else is carried as-is.</auto-generated>
#nullable enable
using Microsoft.EntityFrameworkCore;
using Payments.Domain;

namespace Payments.Infrastructure;

/// Per-service context (database-per-service): only payments's own tables.
public class PaymentsDbContext(DbContextOptions<PaymentsDbContext> options) : DbContext(options)
{
    public DbSet<Payment> Payments => Set<Payment>();
}
