// <auto-generated>Ported from the monolith by port-monolith-dotnet — a verbatim relocation.
// Only the // CW-SEAM[...] markers below need an LLM edit; everything else is carried as-is.</auto-generated>
#nullable enable
using Payments.Domain;
using Payments.Infrastructure;

namespace Payments;

public class PaymentService(PaymentsDbContext db)
{
    public Payment Charge(int orderId, decimal amount)
    {
        var p = new Payment { OrderId = orderId, Amount = amount, Status = "charged" };
        db.Payments.Add(p);
        return p;
    }
}
