// <auto-generated>Ported from the monolith by port-monolith-dotnet — a verbatim relocation.
// Only the // CW-SEAM[...] markers below need an LLM edit; everything else is carried as-is.</auto-generated>
#nullable enable
using System.Net.Http.Json;

namespace Orders.Clients;

/// Typed client to catalog-service (was an in-process call in the monolith).
public interface ICatalogClient
{
    Task<decimal> PriceOfAsync(int productId);
}

public sealed class CatalogClient(HttpClient http) : ICatalogClient
{
    private readonly HttpClient _http = http;

    /// Cross-context read: catalog owns the price, we only copy the scalar.
    public async Task<decimal> PriceOfAsync(int productId)
    {
        using var response = await _http.GetAsync($"/catalog/products/{productId}");
        response.EnsureSuccessStatusCode();
        var product = await response.Content.ReadFromJsonAsync<CatalogProductResponse>();
        return product?.Price
            ?? throw new InvalidOperationException($"catalog-service returned no price for product {productId}");
    }

    private sealed record CatalogProductResponse(int Id, string? Name, decimal Price);
}
