// <auto-generated>Ported from the monolith by port-monolith-dotnet — a verbatim relocation.
// Only the // CW-SEAM[...] markers below need an LLM edit; everything else is carried as-is.</auto-generated>
#nullable enable
using System.Net;
using System.Net.Http.Json;

namespace Orders.Clients;

/// Typed client to customers-service (was an in-process call in the monolith).
public interface ICustomersClient
{
    Task<bool> IsActiveAsync(int id);
}

public sealed class CustomersClient(HttpClient http) : ICustomersClient
{
    private readonly HttpClient _http = http;

    /// Cross-context read: customers owns activation state. An unknown customer is
    /// simply not active — a normal answer, not a fault.
    public async Task<bool> IsActiveAsync(int id)
    {
        using var response = await _http.GetAsync($"/customers/{id}");
        if (response.StatusCode == HttpStatusCode.NotFound)
            return false;

        response.EnsureSuccessStatusCode();
        var customer = await response.Content.ReadFromJsonAsync<CustomerResponse>();
        return customer?.Active ?? false;
    }

    private sealed record CustomerResponse(int Id, string? Name, bool Active);
}
