// <auto-generated>Ported from the monolith by port-monolith-dotnet — a verbatim relocation.
// Only the // CW-SEAM[...] markers below need an LLM edit; everything else is carried as-is.</auto-generated>
#nullable enable
using System.Net;
using System.Net.Http.Json;

namespace Orders.Clients;

/// Typed client to inventory-service (was an in-process call in the monolith).
public interface IInventoryClient
{
    Task<bool> ReserveAsync(int productId, int qty);

    /// Compensation for a reservation this saga already took.
    Task ReleaseAsync(int productId, int qty);
}

public sealed class InventoryClient(HttpClient http) : IInventoryClient
{
    private readonly HttpClient _http = http;

    /// Cross-context write: inventory owns the atomic guarded stock decrement.
    /// 409 means "not enough stock" — an expected outcome, not an error.
    public async Task<bool> ReserveAsync(int productId, int qty)
    {
        using var response = await _http.PostAsJsonAsync(
            "/inventory/reservations", new ReservationRequest(productId, qty));

        if (response.StatusCode is HttpStatusCode.Conflict or HttpStatusCode.NotFound)
            return false;

        response.EnsureSuccessStatusCode();
        var result = await response.Content.ReadFromJsonAsync<ReservationResponse>();
        return result?.Reserved ?? false;
    }

    public async Task ReleaseAsync(int productId, int qty)
    {
        using var response = await _http.PostAsJsonAsync(
            "/inventory/reservations/release", new ReservationRequest(productId, qty));
        response.EnsureSuccessStatusCode();
    }

    private sealed record ReservationRequest(int ProductId, int Quantity);
    private sealed record ReservationResponse(bool Reserved);
}
