// <auto-generated>Ported from the monolith by port-monolith-dotnet — a verbatim relocation.
// Only the // CW-SEAM[...] markers below need an LLM edit; everything else is carried as-is.</auto-generated>
#nullable enable
using System.Net.Http.Json;
using Orders.Contracts;

namespace Orders.Clients;

/// Typed client to payments-service (was an in-process call in the monolith).
public interface IPaymentsClient
{
    Task<Payment> ChargeAsync(int orderId, decimal amount);

    /// Compensation for a charge this saga already authorised.
    Task RefundAsync(int paymentId);
}

public sealed class PaymentsClient(HttpClient http) : IPaymentsClient
{
    private readonly HttpClient _http = http;

    /// Cross-context write: the hardest step to reverse, so the saga runs it LAST.
    public async Task<Payment> ChargeAsync(int orderId, decimal amount)
    {
        using var response = await _http.PostAsJsonAsync(
            "/payments/charges", new ChargeRequest(orderId, amount));
        response.EnsureSuccessStatusCode();

        var payment = await response.Content.ReadFromJsonAsync<Payment>();
        return payment
            ?? throw new InvalidOperationException($"payments-service returned no payment for order {orderId}");
    }

    public async Task RefundAsync(int paymentId)
    {
        using var response = await _http.PostAsync($"/payments/{paymentId}/refund", content: null);
        response.EnsureSuccessStatusCode();
    }

    private sealed record ChargeRequest(int OrderId, decimal Amount);
}
